[package]
name = "ukmm"
version = "0.1.0"
edition = "2021"

[dependencies]


[workspace]
members = [
    "uk-content",
    "uk-mod",
    "uk-reader",
]

[profile.dev]
opt-level = 2

[profile.release]
debug = true