[package]
name = "ukmm"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.62"
base64 = "0.13.0"
chrono = "0.4.22"
clap = { version = "3.2.17", features = ["derive"] }
dircpy = "0.3.12"
dirs2 = "3.0.1"
eframe = { git = "https://github.com/NiceneNerd/egui", package = "eframe" }
egui = { git = "https://github.com/NiceneNerd/egui", package = "egui", features = ["color-hex", "persistence"] }
egui_extras = { git = "https://github.com/NiceneNerd/egui", package = "egui_extras", features = ["image"] }
env_logger = "0.9.0"
flume = "0.10.14"
font-loader = "0.11.0"
fs-err = "2.8.1"
im = "15.1.0"
image = { version = "0.24.4", features = ["jpeg", "png"] }
jwalk = "0.6.0"
join_str = "0.1.0"
log = "0.4.17"
once_cell = "1.13.1"
parking_lot = "0.12.1"
rayon = "1.5.3"
roead = "0.16.2"
ron = "0.8.0"
rustc-hash = "1.1.0"
rstb = { version= "0.3.2", features = ["botw-data"] }
sanitise-file-name = "1.0.0"
serde = { version = "1.0.144", features = ["derive", "rc"] }
serde_json = "1.0.85"
serde_with = "2.0.1"
serde_yaml = "0.9.10"
sevenz-rust = "0.1.1"
smartstring = { version = "1.0.1", features = ["serde"] }
tempfile = "3.3.0"
toml = "0.5.9"
uk-content = { path = "./uk-content" }
uk-mod = { path = "./uk-mod" }
uk-reader = { path = "./uk-reader" }
zip = { version = "0.6.2", default-features = false, features = ["deflate"]}

[target.'cfg(windows)'.dependencies]
remove_dir_all = "0.7.0"

[workspace]
members = [
    "uk-content",
    "uk-mod",
    "uk-reader",
]
