[package]
name = "ukmm"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.62"
dircpy = "0.3.12"
dirs2 = "3.0.1"
env_logger = "0.9.0"
fs-err = "2.8.1"
glob = "0.3.0"
join_str = "0.1.0"
log = "0.4.17"
once_cell = "1.13.1"
parking_lot = "0.12.1"
rayon = "1.5.3"
roead = "0.16.0"
rustc-hash = "1.1.0"
serde = { version = "1.0.144", features = ["derive"] }
serde_yaml = "0.9.10"
toml = "0.5.9"
uk-content = { path = "./uk-content" }
uk-mod = { path = "./uk-mod" }
uk-reader = { path = "./uk-reader" }
zip = { version = "0.6.2", default-features = false, features = ["deflate"]}


[workspace]
members = [
    "uk-content",
    "uk-mod",
    "uk-reader",
]

[profile.dev]
opt-level = 2
