[package]
name = "ukmm"
authors = ["Caleb Smith <c.smith@tuta.io>"]
version = "0.1.2"
edition = "2021"
license = "GPL-3.0-or-later"

[dependencies]
anyhow = "1.0.62"
base64 = "0.13.0"
chrono = "0.4.22"
clap = { version = "3.2.17", features = ["derive"] }
dircpy = "0.3.12"
dirs2 = "3.0.1"
eframe = { git = "https://github.com/NiceneNerd/egui", package = "eframe" }
# egui = { git = "https://github.com/NiceneNerd/egui", package = "egui", default-features = false, features = ["color-hex", "persistence"] }
# egui_extras = { git = "https://github.com/NiceneNerd/egui", package = "egui_extras", features = ["image", "svg"] }
egui_commonmark = { git = "https://github.com/NiceneNerd/egui_commonmark" }
egui_dock = { git = "https://github.com/NiceneNerd/egui_dock" }
egui-notify = { git = "https://github.com/NiceneNerd/egui-notify" }
enum-iterator = "1.2.0"
env_logger = "0.9.0"
flume = "0.10.14"
fs-err = "2.8.1"
im = { version = "15.1.0", features = ["serde"] }
image = { version = "0.24.4", features = ["jpeg", "png"] }
indoc = "1.0"
jwalk = "0.6.0"
join_str = "0.1.0"
log = "0.4.17"
once_cell = "1.13.1"
open = "3.0.3"
parking_lot = { version = "0.12.1", features = ["serde"] }
rayon = "1.5.3"
rfd = "0.10.0"
rustc-hash = "1.1.0"
serde = { version = "1.0.144", features = ["derive", "rc"] }
serde_json = "1.0.85"
serde_yaml = "0.9.13"
smartstring = { version = "1.0.1", features = ["serde"] }
toml = "0.5.9"
uk-content = { path = "./uk-content" }
uk-manager = { path = "./uk-manager" }
uk-mod = { path = "./uk-mod" }
uk-reader = { path = "./uk-reader" }
uk-ui = { path = "./uk-ui" }
zip = { version = "0.6.2", default-features = false, features = ["deflate"]}

[target.'cfg(windows)'.dependencies]
remove_dir_all = "0.7.0"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.12"

[workspace]
members = [
    "uk-content",
    "uk-content-derive",
    "uk-editor",
    "uk-manager",
    "uk-mod",
    "uk-reader",
    "uk-ui",
    "uk-ui-derive"
]
