[package]
name = "ukmm"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.62"
dirs2 = "3.0.1"
env_logger = "0.9.0"
fs-err = "2.8.1"
log = "0.4.17"
once_cell = "1.13.1"
parking_lot = "0.12.1"
roead = "0.16.0"
serde = { version = "1.0.144", features = ["derive"] }
toml = "0.5.9"
uk-content = { path = "./uk-content" }
uk-mod = { path = "./uk-mod" }
uk-reader = { path = "./uk-reader" }

[workspace]
members = [
    "uk-content",
    "uk-mod",
    "uk-reader",
]

[profile.dev]
opt-level = 2
