[package]
name = "ukmm"
description = "A new mod manager for The Legend of Zelda: Breath of the Wild. Successor to BCML."
authors = ["Caleb Smith <c.smith@tuta.io>"]
version = "0.3.1"
edition = "2021"
license = "GPL-3.0-or-later"

[dependencies]
anyhow = "1"
astrolabe = "0.2.0"
base64 = "0.13.0"
dircpy = "0.3.12"
dirs2 = "3"
eframe = { git = "https://github.com/NiceneNerd/egui", package = "eframe", default-features = false, features = ["glow"] }
egui_commonmark = { git = "https://github.com/NiceneNerd/egui_commonmark", features = ["svg", "fetch"] }
egui-notify = { git = "https://github.com/NiceneNerd/egui-notify" }
env_logger = "0.9.0"
flume = "0.10.14"
fs-err = "2.9"
http_req  = {version="^0.9", default-features = false, features = ["rust-tls"]}
image = { version = "0.24.4", features = ["jpeg", "png"] }
jwalk = "0.8.1"
join_str = "0.1.0"
lenient_semver = { version = "0.4.2", features = ["version_serde"] }
log = "0.4.17"
open = "3.0.3"
parking_lot = { version = "0.12.1", features = ["serde"] }
rayon = "1.6"
rfd = "0.11.1"
roxmltree = "0.18.0"
rustc-hash = "1.1.0"
serde = { version = "1", features = ["derive", "rc"] }
serde_json = "1"
serde_yaml = "0.9.13"
smartstring = { version = "1", features = ["serde"] }
uk-content = { path = "crates/uk-content" }
uk-manager = { path = "crates/uk-manager" }
uk-mod = { path = "crates/uk-mod" }
uk-reader = { path = "crates/uk-reader" }
uk-ui = { path = "crates/uk-ui" }
xflags = "0.3.1"
zip = { version = "0.6.2", default-features = false, features = ["deflate"]}

[target.'cfg(windows)'.dependencies]
remove_dir_all = "0.8.1"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.12"

[workspace]
members = [
    "crates/uk-content",
    "crates/uk-content-derive",
    "crates/uk-editor",
    "crates/uk-manager",
    "crates/uk-mod",
    "crates/uk-reader",
    "crates/uk-ui",
    "crates/uk-ui-derive"
]
