[package]
name = "uk-reader"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
dashmap = { version = "5.4.0", features = ["serde"] }
fs-err = "2.9"
include-flate = "0.2.0"
join_str = "0.1.0"
log = "0.4.17"
moka = "0.10.0"
minicbor-ser = "0.1.3"
parking_lot = { version = "0.12.1", features = ["serde"] }
roead = { version = "0.20.2" }
serde = { version = "1.0.137", features = ["derive", "rc"] }
serde_json = "1.0.85"
smartstring = { version = "1", features = ["serde"] }
thiserror = "1.0.31"
typetag = "0.2.1"
uk-content = { path = "../uk-content" }
zarchive = "0.2.0"
