[package]
name = "uk-reader"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.58"
enum_dispatch = "0.3.8"
join_str = "0.1.0"
parking_lot = "0.12.1"
roead = "0.11.1"
serde = { version = "1.0.137", features = ["derive"] }
uk-content = { path = "../uk-content" }
zarchive = "0.1.0"
xxhash-rust = { version = "0.8.5", features = ["xxh3"]}
