[package]
name = "uk-reader"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.58"
join_str = "0.1.0"
once_cell = "1.12.0"
roead = "0.11.1"
serde = { version = "1.0.137", features = ["derive"] }
uk-content = { path = "../uk-content" }
zarchive = "0.1.0"