[package]
name = "uk-mod"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.58"
fs-err = "2.7.0"
join_str = "0.1.0"
jwalk = "0.6.0"
path-slash = "0.2.0"
rayon = "1.5.3"
roead = { version = "0.11.1", features = ["with-serde"] }
serde = { version = "1.0.137", features = ["derive"] }
tempfile = "3.3.0"
tar = "0.4.38"
toml = "0.5.9"
uk-content = { path = "../uk-content" }
uk-reader = { path = "../uk-reader" }
zstd = "0.11.2"
xxhash-rust = { version = "0.8.5", features = ["xxh3"] }
