[package]
name = "uk-mod"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.58"
join_str = "0.1.0"
jwalk = "0.6.0"
lzma = "0.2.2"
rayon = "1.5.3"
roead = { version = "0.10.3", features = ["with-serde"] }
serde = { version = "1.0.137", features = ["derive"] }
toml = "0.5.9"
uk-content = { path = "../uk-content" }
zip = "0.6.2"
