[package]
name = "uk-content"
version = "0.1.0"
edition = "2021"

[dependencies]
indexmap = "1.8.0"
itertools = "0.10.3"
thiserror = "1.0.30"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
strum = "0.24.0"
strum_macros = "0.24.0"

[dependencies.roead]
git = "https://github.com/NiceneNerd/roead"
features = ["with-serde"]
rev = "ff17ad82eaa62ab5986fae9a455c8e5a113f5d19"
