[package]
name = "uk-editor"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
eframe = { git = "https://github.com/NiceneNerd/egui", package = "eframe" }
flume = "0.10.14"
fs-err = "2.9"
jwalk = "0.6.0"
minicbor-ser = "0.2.0"
path-slash = "0.2.1"
parking_lot = "0.12.1"
rayon = "1.6"
rfd = "0.11.1"
roead = { version = "0.20.2", features = ["with-serde", "yaml"] }
uk-content = { path = "../uk-content", features = ["ui"] }
uk-manager = { path ="../uk-manager" }
uk-mod = { path = "../uk-mod" }
uk-ui = { path = "../uk-ui" }
uk-ui-derive = { path = "../uk-ui-derive" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9.17"
ron = "0.8.0"
# serde_yaml = "0.9.14"
