on:
  release:
    types: [created]

jobs:
  release:
    name: Release ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: true
      matrix:
        platform:
          - os: ubuntu-latest
            name: linux
            ext: ~
            arch: tar
          - os: windows-latest
            name: windows
            ext: .exe
            arch: zip
    steps:
      - uses: actions/checkout@master
      - name: Install GTK
        run: sudo apt install libgtk-3-dev
        if: matrix.platform.name == 'linux'
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: Build
        run: cargo +nightly build --release
      - name: Archive Release
        uses: thedoctor0/zip-release@main
        with:
          type: ${{ matrix.platform.arch }}
          filename: ukmm-${{ github.event.release.tag_name }}-${{ matrix.platform.name }}.${{ matrix.platform.arch }}
          path: target/release/ukmm${{ matrix.platform.ext }}
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ukmm-${{ github.event.release.tag_name }}-${{ matrix.platform.name }}.${{ matrix.platform.arch }}
          token: ${{ secrets.GITHUB_TOKEN }}
    env:
      CARGO_PROFILE_RELEASE_CODEGEN_UNITS: 2
