on:
  release:
    types: [created]

jobs:
  release:
    name: Release ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
        platform:
          - os: ubuntu-latest
            name: linux
            ext: ~
            arch: tar
          - os: macos-latest
            name: macos
            ext: ~
            arch: zip
          - os: windows-latest
            name: windows
            ext: .exe
            arch: zip
          - os: ubuntu-20.04
            name: steamdeck
            ext: ~
            arch: tar
    steps:
      - uses: actions/checkout@master
      - name: Install GTK
        run: sudo apt update && sudo apt install libgtk-3-dev
        if: contains(matrix.platform.os, 'ubuntu')
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: Build
        run: cargo +nightly build --release
        env:
          UPDATE_PLATFORM: ${{ matrix.platform.name }}
      - name: UPX Compress Binary
        uses: crazy-max/ghaction-upx@v2.2.0
        if: contains(matrix.platform.os, 'ubuntu')
        with:
          version: v4.0.2
          args: --best --lzma
          files: ./target/release/ukmm${{ matrix.platform.ext }}
      - name: Archive Release
        uses: thedoctor0/zip-release@main
        with:
          type: ${{ matrix.platform.arch }}
          filename: ukmm-${{ github.event.release.tag_name }}-${{ matrix.platform.name }}.${{ matrix.platform.arch }}
          path: ukmm${{ matrix.platform.ext }}
          directory: target/release
      - uses: Shopify/upload-to-release@v1.0.1
        name: Upload artifacts
        with:
          name: ukmm-${{ github.event.release.tag_name }}-${{ matrix.platform.name }}.${{ matrix.platform.arch }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          path: target/release/ukmm-${{ github.event.release.tag_name }}-${{ matrix.platform.name }}.${{ matrix.platform.arch }}
    env:
      CARGO_PROFILE_RELEASE_CODEGEN_UNITS: 1
      CARGO_PROFILE_RELEASE_LTO: "true"
      RUSTFLAGS: "-Zshare-generics -C link-arg=-s"
      OPENSSL_STATIC: 1 
